Bottom sheet navigation
tester-dono/kartograph pull request #1
Opened 2022-05-24 16:31 UTC by tester-dono

# задача [подготовить навигацию](https://www.notion.so/62a65b4c61794e8b8e556dd8d7aae4db?v=1ec45653360a401d9602140d29e7813d&p=12e3c170db9a4d189d88ba32be6b416a)

# Что было сделано:
- загружены все svg
- подготовлены проектые иконки в ProjectIcons
- подготовлены проектые цвета в ProjectColors
- создан виджет  buttomSheetBarNavigation
- изменена навигация под библиотеку routmaster
- дополнен ProjectStrings строками для buttomSheetBarNavigation
- прописал роуты для каждого экрана (Пояснение:в основном для material page, но в будущем можно вставить инициализацию виджетов перед роутом)
# Результат работы
https://user-images.githubusercontent.com/47796424/170704523-1d6b0c36-8171-4e89-b3dd-b8994e682a56.mov

2022-05-26 12:09 UTC, plastb1r commented
Получается, ты его еще будешь переделывать под флаттеровский navbar?

2022-05-27 13:08 UTC, plastb1r requested changes

2022-05-27 13:08 UTC, plastb1r commented on lib/assets/themes/text_style.dart
>  TextStyle textRegular16 = textRegular.copyWith(fontSize: 16.0);
советую засунуть все стили статикой в класс. Так намного легче будет их находить

2022-05-27 13:08 UTC, plastb1r commented on lib/features/debug/screens/debug_screen/debug_screen_widget_model.dart
>  import 'package:kartograph/features/app/di/app_scope.dart';
Если не планируем использовать дебаг экран, то можно его убрать

2022-05-27 13:08 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_route_paths.dart
>    static const String tempScreen = '/tempScreen';
А что за tempScreen? Типа начальный экран? Если так, то и назови соответствующе

2022-05-27 13:08 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_route_paths.dart
>    static const String tempScreen = '/tempScreen';
И нельзя обойтись без него? Сразу на табы или сплеш передавать?

2022-05-27 13:08 UTC, plastb1r commented on pubspec.yaml
> +  routemaster: ^1.0.0
А  routemaster для чего?

2022-05-27 13:14 UTC, tester-dono commented on lib/assets/themes/text_style.dart
>  TextStyle textRegular16 = textRegular.copyWith(fontSize: 16.0);
Так было в шаблоне, но согласен в статике лучше, я так цвета обернул

2022-05-27 13:14 UTC, tester-dono commented on lib/features/debug/screens/debug_screen/debug_screen_widget_model.dart
>  import 'package:kartograph/features/app/di/app_scope.dart';
ок

2022-05-27 13:14 UTC, tester-dono commented on lib/features/navigation/domain/entity/app_route_paths.dart
>    static const String tempScreen = '/tempScreen';
это было тоже в шаблоне, просто думал убирать его или нет

2022-05-27 13:16 UTC, tester-dono commented on pubspec.yaml
> +  routemaster: ^1.0.0
это библиотека, которой я заменил go_router

2022-05-27 13:41 UTC, tester-dono commented on pubspec.yaml
> +  routemaster: ^1.0.0
добавил документацию

2022-05-30 08:48 UTC, plastb1r commented
оо, за теги лайк

2022-05-30 08:48 UTC, plastb1r approved these changes

2022-05-30 11:55 UTC, merged