Экран настроек
tester-dono/kartograph pull request #10
Opened 2022-06-05 16:42 UTC by tester-dono

# задача [ экран настроек](https://www.notion.so/b091c4dfdb1549f5a1eff9ab787eb676)

# Что было сделано:
- была добавлена карточка с опциями
- был сверстан экран настроек
- добавлена минимальная логика на экран настроек

![SettingScreen](https://user-images.githubusercontent.com/47796424/172061015-9a79d69c-162b-45bf-8742-a1fe8b80ce25.gif)

2022-06-06 08:50 UTC, plastb1r requested changes

2022-06-06 08:50 UTC, plastb1r commented on lib/features/setting/screen/setting_screen_wm.dart
> +  StateNotifier<bool> get themeNotifier => _themeNotifier;
давай лучше notifier с типом enum темы: enum theme {light,dark}

2022-06-06 08:50 UTC, plastb1r commented on lib/features/setting/screen/setting_screen_wm.dart
> +      _currentTheme = ProjectStrings.darkTheme;
и убрать строки - заменить на enum

2022-06-06 08:50 UTC, plastb1r commented on lib/features/setting/screen/setting_screen.dart
> +            helperFunc: wm.onTutorialTap,
название лучше на onTap, action замени

2022-06-06 08:50 UTC, plastb1r commented on lib/features/setting/screen/setting_screen.dart
> +class _TutorialWatcherCard extends StatelessWidget {
вроде бы у флаттера есть готовые виджеты для такого дела. Как базовые элементы списка - посмотри

2022-06-06 08:50 UTC, plastb1r commented on lib/features/setting/screen/setting_screen.dart
> +    return CardWidget.withHelper(
и не оч понял, почему это карточка, если это не карточка🤔

2022-06-07 20:17 UTC, tester-dono commented on lib/features/setting/screen/setting_screen.dart
> +class _TutorialWatcherCard extends StatelessWidget {
[CupertinoSwitch](https://api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html)  свитчер по дизайну cupertino
SwitchListTile и ListTile обычные тайлы

2022-06-08 08:38 UTC, tester-dono commented on lib/features/setting/screen/setting_screen.dart
> +    return CardWidget.withHelper(
потому что теперь это карточка

2022-06-08 09:58 UTC, plastb1r commented
еще нужно посмотреть enum'ы для темы

2022-06-29 17:52 UTC, merged