Экран добавления места
tester-dono/kartograph pull request #11
Opened 2022-06-08 08:02 UTC by tester-dono

# задача [ экран создания нового места](https://www.notion.so/8b1a01aead154e00a25eaec77c840747)

# Что было сделано:
- был добавлен виджет выключаемой кнопки
- был добавлен виджет поля ввода с двумя состояниями
- был добавлен виджет выбора из списка
- был сверстан экран  добавления нового места
- добавлена логика  с проверкой ввода на экране создания нового места

2022-06-08 09:56 UTC, plastb1r requested changes

2022-06-08 09:56 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_routes.dart
> +    // '/': (_) =>
закомменченное не нужно?

2022-06-08 09:56 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_routes.dart
> +const Redirect('SettingScreenRoute'),
redirect - это из routemaster?
Можешь кратко описать как он работает?

2022-06-08 09:56 UTC, plastb1r commented on lib/features/place_adding/screen/place_add_screen.dart
> +                child: IntrinsicHeight(
а maimAxisSize: min  не работает?

2022-06-08 09:56 UTC, plastb1r commented on lib/features/place_adding/screen/place_add_screen.dart
> +                        builder: (ctx, value) {
кстати, если аргументы функции не используются, то можно "назвать". их "_"

2022-06-08 09:56 UTC, plastb1r commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +    _currentValue.accept('other');
желательно сдесь тоже с enum поиграться, чтобы были конкретные значения для выпадающего меню, а не строки

2022-06-12 19:21 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen.dart
> +                child: IntrinsicHeight(
если ты про то, чтобы убрать эти два виджета и добавить в column : mainAxisSize: MainAxisSize.min,
то нет, не работает

2022-06-12 19:22 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen.dart
> +                        builder: (ctx, value) {
ctx теперь _

2022-06-12 20:11 UTC, tester-dono commented on lib/features/navigation/domain/entity/app_routes.dart
> +    // '/': (_) =>
наоборот, забыл разкомментить и заменить

2022-06-12 20:11 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +    _currentValue.accept('other');
заменил

2022-06-15 09:12 UTC, plastb1r approved these changes

2022-06-16 11:33 UTC, merged