Экран новых мест
tester-dono/kartograph pull request #12
Opened 2022-06-09 08:48 UTC by tester-dono

Пока только верстка

2022-06-16 11:49 UTC, tester-dono reviewed
в пр вошла api/data но ее можно полностью пропустить, никаких добавлений в ней нет относительно main

2022-06-16 15:44 UTC, plastb1r requested changes

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/screen/places_screeen_wm.dart
> +        return Column(
Давай перенесем все, что связано с ui - в другое место, отдельно от логики. Куда-то в папку widgets или dialogs, например

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/screen/places_screeen_wm.dart
> +      List<StateNotifier<bool>>.generate(
Давай здесь сделаем что-то вроде этого https://github.com/surfstudio/labelcom-flutter/blob/2d5cbcef6b22a1a4c226daff2a284617562911cf/lib/ui/widgets/video/video_controls/data/video_controls_data.dart.
он используется в VideoControls и хранит в себе все флажки состояния, и таким образом будет только один нотифаер на вм и ui, который говорит о состоянии фильтра

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/screen/places_screeen_wm.dart
> +    model.placeStateStream.listen(_updateState);
забыл взять подписку и закрыть при dispose

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/screen/places_screeen_wm.dart
> +    controller.addListener(_searchPlace);
Тоже не закрыто

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/service/bloc/place_bloc.dart
> +      final list = await _rep.getSearchedPlaces(
эти же значения планируются использоваться? если не планируется, то опусти их в самый низ в репозиторий

2022-06-16 15:44 UTC, plastb1r commented on lib/features/places/service/bloc/place_event.dart
> +class PlaceSearchEvent extends BasePlaceEvent {
а сюда  Equatable не нужен?

2022-06-17 08:36 UTC, tester-dono commented on lib/features/places/screen/places_screeen_wm.dart
> +    model.placeStateStream.listen(_updateState);
закрыл в модели

2022-06-17 08:37 UTC, tester-dono commented on lib/features/places/screen/places_screeen_wm.dart
> +    controller.addListener(_searchPlace);
ага, когда домой пришел вспомнил, как будто утюг забыл :)

2022-06-17 11:24 UTC, tester-dono commented on lib/features/places/screen/places_screeen_wm.dart
> +      List<StateNotifier<bool>>.generate(
Возможно покажется оверинженирингом, но я разделил категории и список отображаемых типов мест из категорий + добавил стандартный конструктор, так что добавление нового типа просто состоит из добавления типа в категорию и затем опционально добавление нового типа в стандартный конструктор (все остальное не требует изменений)

2022-06-17 11:27 UTC, tester-dono commented on lib/features/places/service/bloc/place_bloc.dart
> +      final list = await _rep.getSearchedPlaces(
1 - долгота
2 - широта
3 - радиус
лучше посмотреть при связывании получится ли эти элементы откуда то взять, иначе лучше вызвать текущую геолокацию при ините и передавать координаты при отправке элементов

2022-06-17 11:32 UTC, tester-dono commented on lib/features/places/service/bloc/place_event.dart
> +class PlaceSearchEvent extends BasePlaceEvent {
добавил, но он тут не критичен

2022-06-17 11:52 UTC, tester-dono commented on lib/features/places/screen/places_screeen_wm.dart
> +    model.placeStateStream.listen(_updateState);
и в вм

2022-06-17 15:05 UTC, plastb1r requested changes

2022-06-17 15:05 UTC, plastb1r commented on lib/features/places/domain/types_to_show.dart
> +class PlaceTypeToShow {
ChoseCategory, мб?

2022-06-17 15:05 UTC, plastb1r commented on lib/features/places/domain/types_to_show.dart
> +      PlaceTypeToShow(category: Categories.hotel, isChosen: true),
а может обьединить PlaceTypeToShow и Categories в один класс? а то они вклыдываются друг в друга, добавляя по полю (если нет их использования вне контекста выбора - isChosen)

2022-06-20 11:35 UTC, tester-dono commented on lib/features/places/domain/types_to_show.dart
> +  ListPlacesToShow.createStandard() {
default не может быть из за того, что это keyword инит норм

2022-06-20 12:57 UTC, plastb1r commented on lib/features/places/domain/types_to_show.dart
> +      PlaceTypeToShow(category: Categories.hotel, isChosen: true),
ок, тогда оставим как есть

2022-06-20 12:58 UTC, plastb1r approved these changes

2022-06-24 10:47 UTC, merged