Экран добавления маркеров
tester-dono/kartograph pull request #13
Opened 2022-06-17 13:54 UTC by tester-dono

2022-06-20 12:56 UTC, plastb1r requested changes

2022-06-20 12:56 UTC, plastb1r commented on lib/assets/enums/categories.dart
> +  /// цвет категории
дока левая

2022-06-20 12:56 UTC, plastb1r commented on lib/assets/enums/categories.dart
> +  placeAdder('_', Colors.grey, Icons.add_circle);
Это та иконка , которая появляется при тыке на карту?
мб тогда newPlace/emptyPlace

2022-06-20 12:56 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_routes.dart
> +    // '/': (_) =>
непонятные комменты. убери или  добавь доки, если они нужны

2022-06-20 12:56 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_wm.dart
> +    _controller.center = LatLng(35.68, 51.41);
и тут это значение вынести

2022-06-20 12:56 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_screen.dart
> +                if (event is PointerScrollEvent) {
вынеси это в метод вм`ки

2022-06-20 12:56 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_screen.dart
> +                        onPressed: () {},
а эта кнопка заработает ?

2022-06-20 12:56 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_model.dart
> +  /// Create an instance [MapAddingModel].
мне кажется, подобного рода комменты не нужны, тк не добавляют доп инфы, которую сложно выразить кодом. Думаю лучше их не писать. (На многих конструкторах у тебя замечал подобное)

2022-06-21 09:03 UTC, tester-dono commented on lib/assets/enums/categories.dart
> +  placeAdder('_', Colors.grey, Icons.add_circle);
так как это кандидат на новое место, то скорее всего newPlace

2022-06-21 09:12 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_screen.dart
> +                        onPressed: () {},
да, в сборке работает

2022-06-21 09:16 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_model.dart
> +  /// Create an instance [MapAddingModel].
так как это публичный метод, анализатор требует написания хоть какого то комментария

2022-06-21 11:37 UTC, plastb1r requested changes

2022-06-21 11:37 UTC, plastb1r commented on lib/config/coordinates.dart
> +/// Координаты проекта.
может хранить целый LatLng? И по проекто было еще несколько "магических". координат - можно их объединить  в статик класс

2022-06-21 11:37 UTC, plastb1r commented on lib/features/map/screen/map_screen_wm.dart
> +      lat: 31,
А почему кста тут это два отдельных числа, а не общий обьект ?

2022-06-22 08:37 UTC, tester-dono commented on lib/config/coordinates.dart
> +/// Координаты проекта.
эти заменил, остальные магические были скорее всего заменены в сборке

2022-06-22 08:40 UTC, tester-dono commented on lib/features/map/screen/map_screen_wm.dart
> +      lat: 31,
этот класс будет убран на этом экране

2022-06-22 09:50 UTC, plastb1r approved these changes

2022-06-24 10:46 UTC, merged