Feature/assembling
tester-dono/kartograph pull request #14
Opened 2022-06-19 15:18 UTC by tester-dono

2022-06-20 11:20 UTC, tester-dono commented on lib/api/data/place.dart
> +    this.description,
изменил переменные под nulable для передачи их между экранами

2022-06-20 11:20 UTC, tester-dono commented on lib/features/map/widgets/marker_stack.dart
> +          },
теперь каждый маркер переводит на экран изменения конкретного места с карты

2022-06-20 11:20 UTC, tester-dono commented on lib/features/map_adding/map_adding_route.dart
> +            ),
без передачи объектов, передача данных выглядит так

2022-06-20 11:20 UTC, tester-dono commented on lib/features/map_adding/map_adding_route.dart
> +            ),
Также я передаю в wm данные через провайдер, это правильно или нет?

2022-06-20 11:20 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_wm.dart
> +    if (_place.lng != 0 && _place.lng != null) {
так как вероятность того, что координата будет = нулю очень мала, то ее можно ловить при передаче данных между экранами

2022-06-21 08:59 UTC, plastb1r requested changes

2022-06-21 08:59 UTC, plastb1r commented on lib/features/navigation/domain/entity/app_routes.dart
> -    // const Redirect('${AppRoutePaths.tabs}${AppRoutePaths.placesScreen}'),
Кажется осталось с прошлых пр`ов. Непонятно, нужно или нет

2022-06-21 08:59 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_wm.dart
> +  void geo();
Общее правило для нейминга всех методов, что метод - это действие/какое-либо изменение. а тут по названию метода не понятно, что он делает. 
Не стремись упрощать, если это приведет к нехватке информации. Можно назвать getCurrentGeolocation - и в таком случае и дока будет избыточной

2022-06-21 08:59 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_wm.dart
> +    if (_place.lng != 0 && _place.lng != null) {
а в каких моментах у нас может быть "фиктивный" ноль?

2022-06-21 08:59 UTC, plastb1r commented on lib/features/map_adding/map_adding_route.dart
> +            ),
впринципе ок, зависит от подхода. но если решил передавать инфу , которую получаешь из на вигации таким образом, создавая скоупы, то лучше это делать везде.

Но мне кажется в этой ситуации такой подход избыточен - достаточно передать обьект в виджет экрана ведь это не зависимость, которая может меняться, а просто данные для инициализации

2022-06-21 08:59 UTC, plastb1r commented on lib/api/data/place.dart
> +  int? id;
а зачем делать их nullable? типа, если place нет, то можно передать 'Place?', а полноценным обьектом считать тот, в который были переданы все параметры

2022-06-21 22:24 UTC, tester-dono commented on lib/features/navigation/domain/entity/app_routes.dart
> -    // const Redirect('${AppRoutePaths.tabs}${AppRoutePaths.placesScreen}'),
не нужно , просто переход при входе в приложение на табы

2022-06-21 22:27 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_wm.dart
> +  void geo();
согласен,  еще с учетом: что  нейминга метода лучше выбирать глагол, то название в корне не правильно, но с учетом того, что линтер требует, то документацию нужно оставить

2022-06-21 22:29 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_wm.dart
> +    if (_place.lng != 0 && _place.lng != null) {
уже не в каких, изменил навигацию, теперь на экране добавления места, на карту переход осуществляется по средствам стандартного роутера

2022-06-22 09:49 UTC, plastb1r requested changes

2022-06-22 09:49 UTC, plastb1r commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +          placeType: _currentValue.value!,
и нейминг непрозрачный

2022-06-22 09:49 UTC, plastb1r commented on lib/features/place_adding/screen/place_screen_model.dart
> +  final PlaceRepository _rep = PlaceRepository(
так, а у нас нет места, где инициализируются зависимости?
Правильно будет передавать сюда готовый репозиторий

2022-06-22 10:40 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +          placeType: _currentValue.value!,
изменил на _currentTypeValue.value

2022-06-22 10:46 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +          placeType: _currentValue.value!,
при инициализации _currentValue.value принимает обязательный параметр типа места, так что проверка по избыточна

2022-06-22 10:48 UTC, tester-dono commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +          placeType: _currentValue.value!,
в любом случае, если поле будет null, то тип места будет other

2022-06-22 11:45 UTC, plastb1r approved these changes

2022-06-22 12:29 UTC, tester-dono commented on lib/features/place_adding/screen/place_screen_model.dart
> +  final PlaceRepository _rep = PlaceRepository(
теперь они в iscope

2022-06-22 12:44 UTC, plastb1r requested changes

2022-06-22 12:44 UTC, plastb1r commented on lib/features/place_adding/screen/place_add_screen_wm.dart
> +  final StateNotifier<Categories> _currentTypeValue = StateNotifier<Categories>();
давай лучше CategoriesState, а то "текущийТипЗначения" - очень абстрактно

2022-06-22 12:44 UTC, plastb1r commented on lib/features/map_adding/screen/map_adding_wm.dart
> +            'lat': _markers.value![0].lat.toString(),
а почему берем именно нулевой? 
+ тут опасное место, тк _markers может быть null и при этом пустым - в обоих случаях упадет ошибка

2022-06-22 12:59 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_wm.dart
> +            'lat': _markers.value![0].lat.toString(),
массив не мог быть пустым, так как в функции есть проверка на это и он не может содержать [null] так в него добавляется новый элемент, заменяя старый массив, хотя соглашусь, выглядит костыльно

2022-06-22 12:59 UTC, tester-dono commented on lib/features/map_adding/screen/map_adding_wm.dart
> +            'lat': _markers.value![0].lat.toString(),
исправил

2022-06-23 16:24 UTC, plastb1r approved these changes

2022-06-24 09:34 UTC, merged