Рефактор
tester-dono/kartograph pull request #15
Opened 2022-06-30 13:31 UTC by Daniel-Shegida

2022-07-01 10:06 UTC, plastb1r requested changes

2022-07-01 10:06 UTC, plastb1r commented on lib/api/service/place_api/place_api.dart
> +  // @GET(PlaceUrls.place)
Старые запросы больше не нужны?
Тогда удаляй

2022-07-01 10:06 UTC, plastb1r commented on lib/features/places/service/place_rep.dart
> +  // /// Получает место с сервера по id
и тут

2022-07-01 10:06 UTC, plastb1r commented on lib/features/setting/screen/setting_screen_wm.dart
> +    // if (switchFlag) {
ну шо такое, вроде рефакторинг, а комментов только прибавилось..
Они точно нужны?

2022-07-01 10:34 UTC, Daniel-Shegida commented on lib/api/service/place_api/place_api.dart
> +  // @GET(PlaceUrls.place)
ок, удаляю все комменты

2022-07-01 10:35 UTC, Daniel-Shegida commented on lib/features/setting/screen/setting_screen_wm.dart
> +    // if (switchFlag) {
комменты это просто кандидаты на удаление, с одной стороны они не используются, но с другой стороны они написаны и как то жалко удалять

2022-07-01 10:35 UTC, Daniel-Shegida commented on lib/features/setting/screen/setting_screen_wm.dart
> +    // if (switchFlag) {
сейчас удалю

2022-07-01 10:46 UTC, Daniel-Shegida commented on lib/api/service/place_api/place_api.dart
> +  // @GET(PlaceUrls.place)
убрал

2022-07-03 09:50 UTC, plastb1r approved these changes

2022-07-04 07:34 UTC, merged