Feature/migratlon
tester-dono/kartograph pull request #18
Opened 2022-07-05 13:57 UTC by Daniel-Shegida

2022-07-06 07:07 UTC, mpkander requested changes

2022-07-06 07:07 UTC, mpkander commented on lib/features/map/screen/map_adding_screen/map_adding_screen.dart
> +                    '${ProjectStrings.mapSite}${ProjectStrings.mapToken}',
Вот такое лучше выносить от UI как можно дальше. Сейчас логика конкатенации не слишком сложная, ты просто склеиваешь 2 строки. Но это логика в теории может вырасти, могут добавиться новые query-запросы и прочее. 

Готовую строку желательно прокидывать через WM

2022-07-06 07:07 UTC, mpkander commented on lib/features/map/widgets/marker.dart
> +              queryParameters: {
Тут не нравится, что задействованы query-параметры, но при этом нет явного контракта между отправляющим и принимающим, какие данные они отправляю и принимают, соотвественно. 

При изменении имен или состава параметров здесь нарушится логика экрана, на который осуществляется переход. Это нужно унифицировать так, чтобы у принимающего и отдающего был один источник правды

2022-07-06 14:39 UTC, Daniel-Shegida commented on lib/features/map/widgets/marker.dart
> +              queryParameters: {
Итого что было сделано: 
- создан класс NavigationHelper, который содержит все методы переходов на другие экраны(toMap), содержащие требование какие данные и каких типов нужны для этих переходов
- Помещен класс NavigationHelper в IAppScope, из которого и получается этот класс всеми wm
- дополнены все конструкторы требованием NavigationHelper  и заменены все методы перехода в них, на методы NavigationHelper 
- методы принимающие параметры(FromMap) не были добавлены, так как эту функцию осуществляют routes, существующие в каждом директории фичи

2022-07-06 14:42 UTC, Daniel-Shegida commented on lib/features/map/screen/map_adding_screen/map_adding_screen.dart
> +                    '${ProjectStrings.mapSite}${ProjectStrings.mapToken}',
Теперь готовая строка создается в строковом ресурсе (как раньше), но также теперь эту строку получают через wm,

2022-07-08 05:56 UTC, mpkander approved these changes

2022-07-08 05:56 UTC, mpkander commented on lib/features/places/screen/places_screen/places_screeen_wm.dart
> +    _navigationHepper.moveToPlaceDetailScreen(place, context);
Хорошее решение. Мы часто делаем что-то похожее

PS: тут очепятка ещё

2022-07-08 10:07 UTC, merged