Map screen
tester-dono/kartograph pull request #2
Opened 2022-05-25 14:59 UTC by tester-dono

2022-05-26 12:08 UTC, plastb1r requested changes

2022-05-26 12:08 UTC, plastb1r commented on pubspec.yaml
> +  cached_network_image: ^3.2.1
а две нижние зависимости для чего? без них никак?

2022-05-26 12:08 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +                      final url =
это в отдельный метод вынеси, а лучше в утилитарный класс

2022-05-26 12:08 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +                      final url =
это в отдельный метод вынеси, а лучше в утилитарный класс

2022-05-26 12:08 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +        title: const Text(''),
если appbar пустой, то можно его и не использовать

2022-05-26 12:08 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +        title: const Text(''),
если appbar пустой, то можно его и не использовать

2022-05-27 14:23 UTC, tester-dono commented on pubspec.yaml
> +  cached_network_image: ^3.2.1
добавил документацию

2022-05-27 14:38 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +                      final url =
вынес в utils

2022-05-30 12:17 UTC, tester-dono commented on lib/util/map_widget.dart
> +            'https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/$z/$x/$y?access_token=pk.eyJ1IjoidGVzdGVyLWRvbm8iLCJhIjoiY2wzbG1idXVuMW9jZzNkcXdnNGZwN2NlOSJ9.LGGfGe5NuuAyD-FFepK47g';
или весь конструктор начиная от (builder: (context, x, y, z) { ))следует вынести куда то?

2022-05-31 15:57 UTC, plastb1r approved these changes

2022-06-02 09:42 UTC, merged