Логика смены темы из настроек
tester-dono/kartograph pull request #22
Opened 2022-07-07 14:06 UTC by Daniel-Shegida

# задача [Смена темы из настроек](https://www.notion.so/7ba4e2095a4f415ca8038ba60fdb542e)

# Что было сделано:
- был добавлен провайдер для смены настроек
-  был дополнен enum тем для передачи состояния текущей темы
-  был рассмотрен ThemeExtension

# Кратко про ThemeExtension
 К сожалению это просто расширение темы, для использования каких то дополнительных цветовых и не только параметров, позволяющий эти самые параметры плавно переключать через метод lerp
 Относительно смены тем,  максимум что я нашел были следующие дартпады, да и то там просто передается функция, вызывающая setState со сменой флага 
 https://api.flutter.dev/flutter/material/ThemeData/extensions.html
 https://api.flutter.dev/flutter/material/ThemeExtension-class.html
  Так что все равно каким то образом вызывать пересоздания виджета, будь то через setState, то через провайдер с билдером
  
  # Демонстрация  с timeDilation = 5.0;

2022-07-08 07:20 UTC, mpkander requested changes

2022-07-08 07:20 UTC, mpkander commented on lib/features/setting/screen/setting_screen_wm.dart
> +  late final void Function(Themes currentTheme) _changeTheme;
Хорошая практика - делать тайпдефы для таких штук. Либо можешь использовать существующий ValueChanged<T>

2022-07-08 07:20 UTC, mpkander commented on lib/features/setting/domain/themes.dart
> +  /// логическое состояние темы
Неочевидно. Для чего нужно логическое состояние темы? Как оно, например, изменится, если добавятся ещё темы (lightDark, constrast, например)

2022-07-08 10:14 UTC, Daniel-Shegida commented on lib/features/setting/domain/themes.dart
> +  /// логическое состояние темы
Так как в дизайне подразумевается только 2 возможных темы, было решено остановиться на булах для тем, true для темной и false для светлой.
![Снимок экрана 2022-07-08 в 13 08 20](https://user-images.githubusercontent.com/47796424/177971420-980bb7ad-0abf-4483-8b5a-f76abca8acf9.png)
Этот enum я передаю на этот свитчер, который и принимает логическое значение 
``` dart
          StateNotifierBuilder<Themes>(
            listenableState: wm.themeNotifier,
            builder: (ctx, value) {
              return _ThemeChangerCard(
                cardName: value!.themeName,
                swithValue: value.condition,
                onChanged: wm.onChangedTheme,
              );
            },
          ),
```

2022-07-08 10:42 UTC, Daniel-Shegida commented on lib/features/setting/screen/setting_screen_wm.dart
> +  late final void Function(Themes currentTheme) _changeTheme;
сделал typedef

2022-07-11 11:00 UTC, mpkander commented on lib/features/setting/domain/themes.dart
> +  /// логическое состояние темы
Такие моменты желательно документировать. Опять-таки, я представляю как у тебя добавляются новые темы, но при этом остаётся свитчер с тёмной темой (например, может быть несколько вариаций тёмной темы и светлой). Но в таком случае будет неочевидно, зачем нужен этот кондишн 

Я бы вообще это максимально разделил и оставил для тем enum без лишних данных. А уже непосредственно в WM, резолвил бы все дополнительные моменты (имя темы, свитчер и т.д.) в отдельной модельке для UI. Разделяя, это легче поддерживать, твой enum перестаёт зависить от нескольких разных компонентов внутри приложения

Но это не является ошибкой, просто иной подход

2022-07-11 11:00 UTC, mpkander commented on lib/features/setting/screen/setting_screen_wm.dart
>    StateNotifier<Themes> get themeNotifier => _themeNotifier;
Не часть этого кода, но я бы не стал делать Notifier публичным. Подразумевается, что у тебя есть публичный интерфейс ListenableState, который нужно отправлять на UI. Это разделение как раз сделано для того, чтобы избежать сайд-эффектов, при которых ты передаешь мутабельный объект в другое место 

Аналогичным образом можно воспринимать, например, Stream и StreamController. Stream - публичный иммутабельный интерфейс, StreamController - приватный мутабельный

Только если ты не подразумеваешь, что ты через WM делегируешь изменения состояния темы какому-то другому виджету (что не очень в духе концепции Elementary)

2022-07-11 14:15 UTC, Daniel-Shegida commented on lib/features/setting/screen/setting_screen_wm.dart
>    StateNotifier<Themes> get themeNotifier => _themeNotifier;
Понял, заменил везде на ListenableState, на самом деле даже не знал о существовании этого интерфейса

2022-07-11 14:31 UTC, Daniel-Shegida commented on lib/features/setting/domain/themes.dart
> +  /// логическое состояние темы
Добавил документацию

2022-07-11 14:33 UTC, Daniel-Shegida commented on lib/features/setting/domain/themes.dart
> +  /// логическое состояние темы
На самом деле изначально было как ты и сказал в wm, потом мы с Кириллом посмотрели на возможности новых enum и решили добавить данные в них

2022-07-13 10:37 UTC, mpkander approved these changes

2022-07-13 11:11 UTC, merged