добавил добавление и отображение маркеров на карте
tester-dono/kartograph pull request #3
Opened 2022-05-31 10:04 UTC by tester-dono

2022-06-01 12:14 UTC, plastb1r requested changes

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +    widget.controller.dispose();
Обычно, там где создается обьект, то там он и должен dispose`иться. Тут лучше просто отпишись, а диспоуз перенеси на экран

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +  Widget _build(BuildContext context, BoxConstraints constraints) {
не уловил смысла выносить _build из build. Можно там его оставить

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +  Widget _buildMarkerWidget(
Желательно не пользоваться build методами, а переносить их в отдельный виджет, если требуется

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +    children.addAll(markerWidgets);
чет тут логику слишком растянул.
можно сразу return Stack(children: markerWidgets);

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen_wm.dart
> +  final MapController _controller = MapController(
А тут анализатор ругается?
Тип перед переменной кажется лишним

2022-06-01 12:14 UTC, plastb1r commented on lib/features/map/screen/map_screen_wm.dart
> +  final _markers = [
А можно ли эти точки сразу в MapController.location положить?

2022-06-02 09:59 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +    widget.controller.dispose();
дизпоуз контроллера в wm, но анализатор ругается

2022-06-02 10:00 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +    widget.controller.dispose();
удалил и отписал

2022-06-02 10:06 UTC, tester-dono commented on lib/features/map/screen/map_screen_wm.dart
> +  final _markers = [
Нет, потому что по сути это, во первых, будет список объектов Place с координатами, во вторых, у контроллера нет такого поля, он может только получить текущее положение

2022-06-02 10:21 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +  Widget _build(BuildContext context, BoxConstraints constraints) {
исправил в ветке [map-dots-touch](https://github.com/tester-dono/kartograph/tree/map-dots-touch)

2022-06-02 10:21 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +  Widget _buildMarkerWidget(
исправил в ветке [map-dots-touch](https://github.com/tester-dono/kartograph/tree/map-dots-touch)

2022-06-02 10:21 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +    children.addAll(markerWidgets);
исправил в ветке [map-dots-touch](https://github.com/tester-dono/kartograph/tree/map-dots-touch)

2022-06-02 10:23 UTC, tester-dono commented
мне перенести изменения из ветки [map-dots-touch](https://github.com/tester-dono/kartograph/tree/map-dots-touch) сюда или пусть так залью?  (просто там был виджет маркера, так что исправлять там было удобнее)

2022-06-03 11:17 UTC, plastb1r approved these changes

2022-06-03 11:23 UTC, merged