обработал нажатия на маркеры
tester-dono/kartograph pull request #5
Opened 2022-05-31 12:30 UTC by tester-dono

# задача [добавить ивент на нажатия точки на карте](https://www.notion.so/83c8676a174f4d36a139ef373c092cf6)

# Что было сделано:
- вынес маркер в отдельный виджет
- проверил обработку нажатия

2022-06-01 12:25 UTC, plastb1r requested changes

2022-06-01 12:25 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +    return Marker(leftPos: pos.dx, topPos: pos.dy, iconData: icon, color: color);
Как говорил в https://github.com/tester-dono/kartograph/pull/3, лучше избавляться от билд методов. А тут он вообще в одну строку

2022-06-01 12:25 UTC, plastb1r commented on lib/features/map/widgets/marker.dart
> +class Marker extends StatelessWidget {
А в чем состоит суть задачи?
Вроде как ты вынес метод, но обработка остается в пределах тега.
Мб в Marker передавать VoidCallback на нажатие?

2022-06-02 10:26 UTC, tester-dono commented
исправил

2022-06-03 11:17 UTC, plastb1r approved these changes

2022-06-03 11:21 UTC, merged