виджеты на карте
tester-dono/kartograph pull request #6
Opened 2022-05-31 15:26 UTC by tester-dono

# задача [Создать виджеты иконок на карте](https://www.notion.so/0006626c5c8341b9a4cd77a4c277df0e)
# Что было сделано:
- 3 виджета в row и column 

![Снимок экрана 2022-05-31 в 18 22 13](https://user-images.githubusercontent.com/47796424/171210532-fd640bd3-f2f2-4e71-922d-d82818a425bd.png)

2022-06-06 08:42 UTC, plastb1r requested changes

2022-06-06 08:42 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +  Widget build(BuildContext context) {
этот билд метод в других изменениях уберется?
Вроде говорили, что его убрали

2022-06-06 08:42 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +                            _RoundMapButton(svgPath: ProjectIcons.refresh,),
Давай их лучше в отдельные файлы засунем.
плюс с форматированием что-то не так

2022-06-06 08:42 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +            onTapUp: (details) {
Давай здесь сделаем в качестве коллбека один вызов метода из вмки
onTapUp: wm.onMapTapUp - что- то такое

2022-06-07 19:36 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +  Widget build(BuildContext context) {
да, был не сделан update

2022-06-07 19:54 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +            onTapUp: (details) {
там mapTransformer используется, так что не очень понятно как это сделать

2022-06-08 09:59 UTC, plastb1r commented
осталось поменять onTapUp и все

2022-06-08 09:59 UTC, plastb1r approved these changes

2022-06-12 18:51 UTC, merged