Feature/server api
tester-dono/kartograph pull request #7
Opened 2022-06-03 08:05 UTC by tester-dono

# задача [реализовать постановку точек](https://www.notion.so/0aa86821041142819ab61d8ef78d47b8)

# Что было сделано:
- Cоздан класс отображающий стек маркеров
- ValueListenableBuilder не помог
- Маркеры добавлены в wm

# Результат работы

https://user-images.githubusercontent.com/47796424/171154977-f73ba954-c514-4e1d-a7eb-e32fbe446a86.mov

2022-06-10 15:55 UTC, plastb1r requested changes

2022-06-10 15:55 UTC, plastb1r commented on lib/features/places/screen/places_screen.dart
> +void testFuncs() async {
что-то тебе очень нравится называть методы функциями))
называй их по задаче/действию, которые они выполняют

2022-06-10 15:55 UTC, plastb1r commented on lib/features/places/screen/places_screen.dart
> +  final PlaceRepository rep = PlaceRepository(RestClient(Dio()));
инициализация бизнес логики не должна быть на экране

2022-06-12 18:50 UTC, tester-dono commented on lib/features/places/screen/places_screen.dart
> +void testFuncs() async {
хпхпх. ну да, так и есть, но на самом деле это просто метод, который тестирует функции из репозитория, он и не нужен в ветке

2022-06-12 18:50 UTC, tester-dono commented on lib/features/places/screen/places_screen.dart
> +  final PlaceRepository rep = PlaceRepository(RestClient(Dio()));
удалено

2022-06-15 09:10 UTC, plastb1r approved these changes

2022-06-16 11:36 UTC, merged