Сделана геолокация
tester-dono/kartograph pull request #9
Opened 2022-06-03 13:38 UTC by tester-dono

![Снимок экрана 2022-06-03 в 16 35 14](https://user-images.githubusercontent.com/47796424/171865298-4a1a4cb6-d7ac-4ba4-92ae-9684f2e7bb70.png)

2022-06-07 08:49 UTC, plastb1r requested changes

2022-06-07 08:49 UTC, plastb1r commented on lib/features/map/screen/map_screen.dart
> +        widget.markers.map(widget.transformer.fromLatLngToXYCoords);
попробуй засунуть это в didUpdateWidget, чтобы он не пересчитывал все точки на каждый билд

2022-06-07 08:49 UTC, plastb1r commented on lib/features/map/screen/map_screen_wm.dart
> +    var test = model.mapStateStream;
что тестируем?)

2022-06-07 08:49 UTC, plastb1r commented on lib/features/map/service/map_state.dart
> +  final Kostil = DateTime.now();
совсем непонятное место. а если состояние не изменилось - зачем его обновлять?

2022-06-07 08:49 UTC, plastb1r commented on lib/features/places/screen/places_screen.dart
> +Future<void> _determinePosition() async {
в идеале, это в сервисы вынести, но давай хотя бы в модель перенесем - такой логике на ui не место

2022-06-07 19:59 UTC, tester-dono commented on lib/features/map/service/map_state.dart
> +  final Kostil = DateTime.now();
например человек остался на месте и решил просто переместить куда то карту и нажать на гео,  чтобы вернуться на картах к текущему местоположению, тогда придет одинаковый state с  одинаковой геолокацией и блок его самостоятельно выкинет (так как стейт был бы идентичным с другим)

2022-06-07 20:01 UTC, tester-dono commented on lib/features/map/service/map_state.dart
> +  final Kostil = DateTime.now();
на сколько я помню это решается или просто уникальным полем, типа id или временем,  чтобы стейты были различны с другими, или изменением самих настроек блока (но я не  уверен, как это сделать)

2022-06-07 20:02 UTC, tester-dono commented on lib/features/map/screen/map_screen_wm.dart
> +    var test = model.mapStateStream;
а вот внимательном ревьювера ))))

2022-06-07 20:02 UTC, tester-dono commented on lib/features/map/screen/map_screen_wm.dart
> +    var test = model.mapStateStream;
сорян, буду в следующий раз все таки просматривать свой пр

2022-06-07 20:09 UTC, tester-dono commented on lib/features/places/screen/places_screen.dart
> +Future<void> _determinePosition() async {
не, это просто экран, на котором тестировал геолокацию, скорее всего его лучше удалить

2022-06-08 12:13 UTC, tester-dono commented on lib/features/map/screen/map_screen.dart
> +        widget.markers.map(widget.transformer.fromLatLngToXYCoords);
тем более, это же как анимация перемещения виджетов, так что она так или иначе в пересчитывался на каждый бил

2022-06-08 16:10 UTC, plastb1r approved these changes

2022-06-12 19:00 UTC, merged